config/routes.rb
Covenantchoir::Application.routes.draw do
  devise_for :members
  get "home/index"
  devise_for :views
  resources :members

  devise_for :users
    root "home#index"
    resources :users
    resources :attendances

  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :member
	
	has_many :record
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attendance }
      else
        format.html { render action: 'new' }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:member, :event)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member %><br>
    <%= f.text_field :member %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Member</th>
      <th>Event</th>
      <p>Date<div class="well">
  <div id="datetimepicker2" class="input-append">
    <input data-format="MM/dd/yyyy HH:mm:ss PP" type="text"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
</div>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'en',
      pick12HourFormat: true
    });
  });
</script></th>
      <th>No. of Attendance
      </p>
      
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.member %></td>
        <td><%= attendance.event %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @attendance.member %>

  <%= form_for @member do |f| %>
<ul> <% @attendance.@records.each do |record| %>
	<p>
	<%= check_box_tag("record",record.id) %>
	<%= record.name %>
	</p>

<% end %></ul>
<%=form_for([@attendance,@attendance.records.build]) do |f| %>
<% end %>
<div class="actions"><%= f.submit 'Add record!!!' %> </div>
<% end %>
</p>

<p>
  <strong>Event:</strong>
  <%= @attendance.record %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>